// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public interface LocalInferenceEngineEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:android_studio.LocalInferenceEngineEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .android_studio.LocalInferenceEngineEvent.EventType event_type = 1;</code>
   * @return Whether the eventType field is set.
   */
  boolean hasEventType();
  /**
   * <code>optional .android_studio.LocalInferenceEngineEvent.EventType event_type = 1;</code>
   * @return The eventType.
   */
  com.google.wireless.android.sdk.stats.LocalInferenceEngineEvent.EventType getEventType();

  /**
   * <code>optional string error_message = 2;</code>
   * @return Whether the errorMessage field is set.
   */
  boolean hasErrorMessage();
  /**
   * <code>optional string error_message = 2;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <code>optional string error_message = 2;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <pre>
   * Process exit code (meaningful for SERVER_CRASH)
   * </pre>
   *
   * <code>optional int32 exit_code = 3;</code>
   * @return Whether the exitCode field is set.
   */
  boolean hasExitCode();
  /**
   * <pre>
   * Process exit code (meaningful for SERVER_CRASH)
   * </pre>
   *
   * <code>optional int32 exit_code = 3;</code>
   * @return The exitCode.
   */
  int getExitCode();

  /**
   * <pre>
   * Hardware capabilities detected by llama-server
   * </pre>
   *
   * <code>optional .android_studio.LocalInferenceEngineEvent.HardwareCapabilities hardware_capabilities = 5;</code>
   * @return Whether the hardwareCapabilities field is set.
   */
  boolean hasHardwareCapabilities();
  /**
   * <pre>
   * Hardware capabilities detected by llama-server
   * </pre>
   *
   * <code>optional .android_studio.LocalInferenceEngineEvent.HardwareCapabilities hardware_capabilities = 5;</code>
   * @return The hardwareCapabilities.
   */
  com.google.wireless.android.sdk.stats.LocalInferenceEngineEvent.HardwareCapabilities getHardwareCapabilities();
  /**
   * <pre>
   * Hardware capabilities detected by llama-server
   * </pre>
   *
   * <code>optional .android_studio.LocalInferenceEngineEvent.HardwareCapabilities hardware_capabilities = 5;</code>
   */
  com.google.wireless.android.sdk.stats.LocalInferenceEngineEvent.HardwareCapabilitiesOrBuilder getHardwareCapabilitiesOrBuilder();

  /**
   * <code>optional .android_studio.LocalInferenceEngineEvent.FailureReason failure_reason = 6;</code>
   * @return Whether the failureReason field is set.
   */
  boolean hasFailureReason();
  /**
   * <code>optional .android_studio.LocalInferenceEngineEvent.FailureReason failure_reason = 6;</code>
   * @return The failureReason.
   */
  com.google.wireless.android.sdk.stats.LocalInferenceEngineEvent.FailureReason getFailureReason();
}
